WIWI/config/routes.rb
Rails.application.routes.draw do
  resources :shifts
  get 'shifts/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

WIWI/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

WIWI/app/models/shift.rb
class Shift < ApplicationRecord
end

WIWI/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

WIWI/app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def index
      @shifts = HTTParty.get('https://api.wheniwork.com/2/shifts',
      :headers =>{'Content-Type' => 'application/json'} )
    end
end

WIWI/app/helpers/application_helper.rb
module ApplicationHelper
end

WIWI/app/helpers/shifts_helper.rb
module ShiftsHelper
end

WIWI/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WIWI</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

WIWI/app/views/shifts/_form.html.erb
<%= form_with(model: shift, local: true) do |form| %>
  <% if shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :userId %>
    <%= form.text_field :userId, id: :shift_userId %>
  </div>

  <div class="field">
    <%= form.label :positionId %>
    <%= form.text_field :positionId, id: :shift_positionId %>
  </div>

  <div class="field">
    <%= form.label :startTime %>
    <%= form.text_field :startTime, id: :shift_startTime %>
  </div>

  <div class="field">
    <%= form.label :endTime %>
    <%= form.text_field :endTime, id: :shift_endTime %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes, id: :shift_notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

WIWI/app/views/shifts/edit.html.erb
<h1>Editing Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

WIWI/app/views/shifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shifts</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Positionid</th>
      <th>Starttime</th>
      <th>Endtime</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.userId %></td>
        <td><%= shift.positionId %></td>
        <td><%= shift.startTime %></td>
        <td><%= shift.endTime %></td>
        <td><%= shift.notes %></td>
        <td><%= link_to 'Show', shift %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path %>

WIWI/app/views/shifts/new.html.erb
<h1>New Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Back', shifts_path %>

WIWI/app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @shift.userId %>
</p>

<p>
  <strong>Positionid:</strong>
  <%= @shift.positionId %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @shift.startTime %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @shift.endTime %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @shift.notes %>
</p>

<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>